// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAdb() {
  return window['go']['main']['App']['CheckAdb']();
}

export function GetAppIcon(arg1) {
  return window['go']['main']['App']['GetAppIcon'](arg1);
}

export function GetBloatwareList(arg1) {
  return window['go']['main']['App']['GetBloatwareList'](arg1);
}

export function GetDeviceInfo(arg1) {
  return window['go']['main']['App']['GetDeviceInfo'](arg1);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetPackages(arg1) {
  return window['go']['main']['App']['GetPackages'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UninstallPackage(arg1, arg2) {
  return window['go']['main']['App']['UninstallPackage'](arg1, arg2);
}
