// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAdb():Promise<boolean>;

export function GetAppIcon(arg1:string):Promise<string>;

export function GetBloatwareList(arg1:string):Promise<Array<main.BloatPackage>>;

export function GetDeviceInfo(arg1:string):Promise<Record<string, string>>;

export function GetDevices():Promise<Array<string>>;

export function GetPackages(arg1:string):Promise<Array<main.AppInfo>>;

export function Greet(arg1:string):Promise<string>;

export function UninstallPackage(arg1:string,arg2:string):Promise<void>;
